# Generated by Django 3.0.5 on 2020-05-06 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonefield',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 13 digits', regex='^\\d{9,13}$')]),
        ),
    ]
