# Generated by Django 3.0.7 on 2020-06-27 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20200505_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneField',
        ),
    ]
