# Generated by Django 3.0.7 on 2020-07-14 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(default='', max_length=100, verbose_name='Institution')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Description')),
                ('from_period', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='From Period')),
                ('until_period', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Until Period')),
            ],
            options={
                'verbose_name': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, verbose_name='Name')),
                ('birth', models.DateField(default=datetime.date(1997, 7, 20), verbose_name='Born')),
                ('mail', models.EmailField(default='', max_length=255, verbose_name='Mail')),
                ('languages', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'English'), (2, 'Chinese'), (3, 'Portuguese')], default=0, verbose_name='Languages')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None, verbose_name='Phone')),
                ('link', models.URLField(blank=True, default='', max_length=100, verbose_name='Other Platform')),
                ('about', models.TextField(blank=True, default='', max_length=2000, verbose_name='About')),
                ('current_goals', models.TextField(blank=True, default='', max_length=1000, verbose_name='Current Goals')),
                ('proffessional_description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Professional Description')),
                ('last', models.DateTimeField(auto_now=True, unique=True, verbose_name='Last Modification')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='AdditionalEducation',
            fields=[
                ('education_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cv.Education')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Additional Education',
                'verbose_name_plural': 'Additional Education',
            },
            bases=('cv.education',),
        ),
        migrations.CreateModel(
            name='XP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=100, unique=True, verbose_name='Company')),
                ('role', models.CharField(default='', max_length=100, verbose_name='Role')),
                ('main_activities', models.CharField(default='', max_length=100, verbose_name='Main Activities')),
                ('from_period', models.DateField(default=django.utils.timezone.now, verbose_name='From Period')),
                ('until_period', models.DateField(default=django.utils.timezone.now, verbose_name='Until Period')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Professional Experience',
                'verbose_name_plural': 'Professional Experiences',
            },
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Profile', verbose_name='Profile'),
        ),
    ]
