# Generated by Django 3.0.7 on 2020-08-12 03:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, verbose_name='Name')),
                ('born_in', models.DateField(default=datetime.date(1997, 8, 18), verbose_name='Born In')),
                ('mail', models.EmailField(default='', max_length=255, verbose_name='Mail')),
                ('languages', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'English'), (2, 'Chinese'), (3, 'Portuguese')], default=0, verbose_name='Languages')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None, verbose_name='Phone')),
                ('link', models.URLField(blank=True, default='', verbose_name='Other Platform')),
                ('about', models.TextField(blank=True, default='', max_length=2000, verbose_name='About')),
                ('current_goals', models.TextField(blank=True, default='', max_length=1000, verbose_name='Current Goals')),
                ('proffessional_description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Professional Description')),
                ('last', models.DateTimeField(auto_now=True, unique=True, verbose_name='Last Modification')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='XP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=100, unique=True, verbose_name='Company Name')),
                ('company_description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Company Description')),
                ('company_website', models.URLField(blank=True, default='', verbose_name='Company Website')),
                ('company_mail', models.EmailField(blank=True, default='', max_length=255, verbose_name='Company Mail')),
                ('company_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, region=None, verbose_name='Company Phone')),
                ('employee_role', models.CharField(default='', max_length=100, verbose_name='Role')),
                ('employee_main_activity', models.TextField(default='', max_length=500, verbose_name='Main Activities')),
                ('from_period', models.DateField(default='', verbose_name='From Period')),
                ('until_period', models.DateField(default='', verbose_name='Until Period')),
                ('is_current', models.BooleanField(blank=True, default=False, verbose_name='Is Current')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Professional Experience',
                'verbose_name_plural': 'Professional Experiences',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(default='', max_length=100, verbose_name='Institution')),
                ('institution_description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Company Description')),
                ('institution_website', models.URLField(blank=True, default='', verbose_name='Company Website')),
                ('institution_mail', models.EmailField(blank=True, default='', max_length=255, verbose_name='Company Mail')),
                ('institution_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=255, region=None, verbose_name='Company Phone')),
                ('course', models.CharField(blank=True, default='', max_length=100, verbose_name='Course')),
                ('course_description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Course Description')),
                ('from_period', models.DateField(default='', null=True, verbose_name='From Period')),
                ('until_period', models.DateField(default='', null=True, verbose_name='Until Period')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Duration')),
                ('is_current', models.BooleanField(blank=True, default=False, verbose_name='Is Current')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Education',
            },
        ),
    ]
