# Generated by Django 3.0.7 on 2020-06-27 06:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='', max_length=2000, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='profile',
            name='born',
            field=models.DateField(default=datetime.date.today, unique=True, verbose_name='Born'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_goals',
            field=models.TextField(default='', max_length=1000, verbose_name='Current Goals'),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.CharField(choices=[(0, 'None'), (1, 'English'), (2, 'Chinese'), (3, 'Portuguese')], default='', max_length=30, verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.URLField(default='', max_length=100, verbose_name='Other Platform'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 13 digits', regex='^\\d{9,13}$')], verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='profile',
            name='proffessional_description',
            field=models.TextField(default='', max_length=1000, verbose_name='Professional Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mail',
            field=models.EmailField(default='', max_length=255, unique=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='XP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=100, unique=True, verbose_name='Company')),
                ('role', models.CharField(default='', max_length=100, verbose_name='Role')),
                ('main_activities', models.CharField(default='', max_length=100, verbose_name='Main Activities')),
                ('from_period', models.DateField(auto_now_add=True, verbose_name='From Period')),
                ('until_period', models.DateField(auto_now_add=True, verbose_name='Until Period')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Professional Experience',
                'verbose_name_plural': 'Professional Experiences',
            },
        ),
        migrations.CreateModel(
            name='Certified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatcher', models.CharField(default='', max_length=100, verbose_name='Dispatcher')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Description')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Duration')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Extra Curricular Course',
                'verbose_name_plural': 'Extra Curricular Courses',
            },
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=100, verbose_name='School')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Description')),
                ('from_period', models.DateField(auto_now_add=True, verbose_name='From Period')),
                ('until_period', models.DateField(auto_now_add=True, verbose_name='Until Period')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Academic Training',
            },
        ),
    ]
