# Generated by Django 3.0.7 on 2020-08-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xp',
            old_name='empolyee_main_activity',
            new_name='employee_main_activity',
        ),
    ]
