# Generated by Django 3.0.7 on 2020-07-02 20:03

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20200627_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last',
            field=models.TimeField(default='', unique=True, verbose_name='Last Modification'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='born',
            field=models.DateField(default=datetime.date(1997, 7, 8), unique=True, verbose_name='Born'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_goals',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Current Goals'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'English'), (2, 'Chinese'), (3, 'Portuguese')], default=0, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link',
            field=models.URLField(blank=True, default='', max_length=100, verbose_name='Other Platform'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proffessional_description',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='Professional Description'),
        ),
    ]
