# Generated by Django 3.0.7 on 2020-07-02 20:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200702_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None, verbose_name='Phone'),
        ),
    ]
