# Generated by Django 3.0.7 on 2020-07-02 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200702_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='born',
            field=models.DateField(default=datetime.date(1997, 7, 8), verbose_name='Born'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mail',
            field=models.EmailField(default='', max_length=255, verbose_name='Mail'),
        ),
    ]
