# Generated by Django 3.0.7 on 2020-07-02 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20200702_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last',
            field=models.DateTimeField(default=datetime.datetime.now, unique=True, verbose_name='Last Modification'),
        ),
    ]
