# Generated by Django 3.0.7 on 2020-07-03 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20200702_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(default='', max_length=100, verbose_name='Institution')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Description')),
                ('from_period', models.DateField(default=django.utils.timezone.now, verbose_name='From Period')),
                ('until_period', models.DateField(default=django.utils.timezone.now, verbose_name='Until Period')),
            ],
            options={
                'verbose_name': 'Education',
            },
        ),
        migrations.RemoveField(
            model_name='certified',
            name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(default=datetime.date(1997, 7, 9), verbose_name='Born'),
        ),
        migrations.AlterField(
            model_name='xp',
            name='from_period',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='From Period'),
        ),
        migrations.AlterField(
            model_name='xp',
            name='until_period',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Until Period'),
        ),
        migrations.CreateModel(
            name='AdditionalEducation',
            fields=[
                ('education_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cv.Education')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Additional Education',
                'verbose_name_plural': 'Additional Education',
            },
            bases=('cv.education',),
        ),
        migrations.DeleteModel(
            name='Academic',
        ),
        migrations.DeleteModel(
            name='Certified',
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Profile', verbose_name='Profile'),
        ),
    ]
