# Generated by Django 3.0.7 on 2020-07-04 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20200703_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='from_period',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='From Period'),
        ),
        migrations.AlterField(
            model_name='education',
            name='until_period',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Until Period'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last',
            field=models.DateTimeField(auto_now=True, unique=True, verbose_name='Last Modification'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=40, verbose_name='Name'),
        ),
    ]
